title: Katie's Website
author: Katie
description: Stuff I wanted to share.
show_downloads: true
logo: /favicon.svg
last_updated: 2025-10-16 08:54:23 -0700
plugins:
  - jekyll-seo-tag
include:
  - .well-known
